### ISSUE TITLE
Build errors with uwsgi 2.0.9

### ISSUE THREAD

**Issue by grivescorbett** [unbit/uwsgi-sse-offload#1]
I've built uwsgi 2.0.9 from source using the command `python uwsgiconfig.py --build` and then tried to build this plugin using `./uwsgi --build-plugin plugins/uwsgi-sse-offload`.  I'm getting these errors: https://gist.github.com/grivescorbett/75600e82b22596a5d3ef

Looks like `struct uwsg_route` is not being defined but if I do a `cat uwsgi.h` I see it's declaration in there.  Is there a build step I'm missing?

**Comment by unbit** [comment]
Hi, you have built your uWSGI instance without internal routing support (you should have a pretty scaring warning about it when you run uWSGI). Install libpcre development package (libpcre3-dev or libpcre-devel) and rebuild uWSGI.

**Comment by grivescorbett** [comment]
Thanks!
